/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TRIG_H_RPCGEN
#define _TRIG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define TRIG 0x80000001
#define VTRIG 1

#if defined(__STDC__) || defined(__cplusplus)
#define seno 1
extern  double * seno_1(double , CLIENT *);
extern  double * seno_1_svc(double , struct svc_req *);
#define coseno 2
extern  double * coseno_1(double , CLIENT *);
extern  double * coseno_1_svc(double , struct svc_req *);
extern int trig_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define seno 1
extern  double * seno_1();
extern  double * seno_1_svc();
#define coseno 2
extern  double * coseno_1();
extern  double * coseno_1_svc();
extern int trig_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TRIG_H_RPCGEN */
