/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "trig.h"
#include<stdlib.h> // añadido

void
trig_1(char *host, double d ) // añadido
{
	CLIENT *clnt;
	double  *result_1;
	double seno_1_arg1=d; // añadido: = d
	double  *result_2;
	double coseno_1_arg1=d; // añadido = d

#ifndef	DEBUG
	clnt = clnt_create (host, TRIG, VTRIG, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = seno_1(seno_1_arg1, clnt);
	if (result_1 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("seno( %f ) = %f \n", d, *result_1); // añadido
	result_2 = coseno_1(coseno_1_arg1, clnt);
	if (result_2 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("coseno( %f ) = %f \n", d, *result_2); // añadido
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	/* añadido: argv[0] <--> nombre_archivo_ejecutable */

	if (argc < 2) {
		printf ("Usage: %s server_host angulo \n", argv[0]); // añadido: angulo
		exit (1);
	}
	host = argv[1]; /* añadido: argv[1] <--> servidor */
	trig_1 (host,atof(argv[2])); /* añadido: atof(argv[2]) */
	/*añadido: argv[2] <--> angulo */
return 0;
}
