/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "trig.h"
#include<math.h> //añadido

double *
seno_1_svc(double arg1,  struct svc_req *rqstp)
{
	static double  result;
	/* server code: añadido */
	result = sin(arg1);
	return &result;
}

double *
coseno_1_svc(double arg1,  struct svc_req *rqstp)
{
	static double  result;
	/* server code: añadido */
	result = cos(arg1);
	return &result;
}
